name: 01 - building blcoks

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Hello World Step
        run : echo "Hello World!!!"
  
  Test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Success step
        run : | 
          echo "This step will success"
          exit 0
      - name: Good Bye Step
        run : echo "Good Bye!!!"