name: 02 - Workflow Event Trigger

on:
  pull_request:
  workflow_dispatch:

jobs:
  workflow-job-event:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow job event
        run: echo "This is a workflow job event triggered by a ${{ github.event_name }}."