name: 03 - workfrlow runners

on: push 

jobs:
  ubuntu-runner:
    runs-on: ubuntu-latest
    steps:
      - name: It's runns on ubuntu-latest
        run : |
         echo "Hello World"
         echo "This workflow is running on ubuntu-latest runner: $RUNNER_OS"

  windows-runner:
    runs-on: windows-latest
    steps:
      - name: It's runns on windows-latest
        run : |
          echo "Hello World"
          echo "This workflow is running on windows-latest runner: $RUNNER_OS"
