name: 03 - workfrlow runners

on: workflow_dispatch 

jobs:
  ubuntu-runner:
    runs-on: ubuntu-latest
    steps:
      - name: It's runns on ubuntu-latest
        run : |
         echo "Hello World"
         echo "This workflow is running on ubuntu-latest runner: $RUNNER_OS"

  windows-runner:
    runs-on: windows-latest
    steps:
      - name: It's runns on windows-latest
        shell: bash
        run : |
           echo "Hello World"
           echo "This workflow is running on windows-latest runner: $RUNNER_OS"
  mac-runner:
    runs-on: macos-latest
    steps:
      - name: It's runns on macos-latest
        run : |
           echo "Hello World"
           echo "This workflow is running on macos-latest runner: $RUNNER_OS"